# AICE1006 - Data Analytics

## Lecture 2 - Numpy: Numerical Python


**Zhiwu Huang**  <br/>
Lecturer (Assistant Professor) <br/>
Vision, Learning and Control (VLC) Research Group <br/>
School of Electronics and Computer Science (ECS) <br/>
University of Southampton<br/>

*Office Hour: Wed 2PM-3PM, Please book in advance.* <br/>
``Zhiwu.Huang@soton.ac.uk``

<br/>
<br/>
<!-- <br/> -->

Credit: Marco Forgione, Researcher, USI-SUPSI


<!-- The workhorse of numerical mathematics and machine learning in Python -->


## AICE1006-Coursework II (Python): Evaluation (TBD)


Grades are based on a **presentation** to be prepared using the jupyter/python environment. You will put in practice the data cleanup, preparation, visualization, and analysis techniques discussed in this course **on a dataset of your choice**.

* You will work in **one of six/seven groups** (exceptions to be agreed with the teacher).
* Submit the name/surname of the group members at **Handin Link by March 28**.
* During **the last 3 lectures** of the Data Analytics module, each group will deliver a 10-minute talk followed by a 5-minute Q&A session.
* Group presentation order will be **randomly extracted**. 
* Submit the final report at **Handin Link by May 16**.
* In general, the members of a group will receive **the same grade**.
* If the group members eventually prefer to be graded separately, they should communicate their decision as soon as possible, prepare substantially different works, and deliver separate talks.

## Recap

In the previous lecture:

* We discussed the overall objective of the data challenge module
* We introduced Jupyter notebook
* We reviewed some Python basics



Today, we introduce one of the most important libraries for scientific computation in Python: **numpy**.

## Numpy in a nutshell

Provides data structures & algorithms for numerical mathematics needed in most scientific applications in Python

* An efficient multidimensional array: ```ndarray```
* Function performing mathematical operations on arrays
* Linear algebra, Fourier transform, ...
* Fast  *vectorized* array operations

## Getting started with numpy

Let us import the ``numpy`` module and give it the shorthand name ``np``. This is a standard convention!

In [1]:
import numpy as np

In [2]:
# Let us define some arrays
x1 = np.random.randint(10, size=6)  # One-dimensional array (aka vector)
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array (aka matrix)

In [3]:
type(x1), type(x2)

(numpy.ndarray, numpy.ndarray)

In [4]:
x1 # a 1D numpy array ("vector")

array([3, 8, 1, 4, 2, 6])

In [5]:
x2 # a matrix ("matrix")

array([[9, 9, 7, 2],
       [5, 7, 3, 3],
       [5, 8, 9, 3]])

In *Linear Algebra* you have called the 1D array **vector**. You will call the 2D array **matrix**.

##  Why numpy?

In principle, we can implement math operations in plain Python (using the ``math`` module):

In [6]:
import math

x_list = [math.sin(x) for x in range(100000)] # math operation in plain python

Same operation in ``numpy``:

In [7]:
x_np = np.sin(np.arange(100000)) # same math operation in numpy 

In [8]:
x_list == x_np # numerical result is the same

array([ True,  True,  True, ...,  True,  True,  True])

The result is the same, but performance changes dramatically!

In [9]:
%timeit -n 50 x_list = [math.sin(x) for x in range(100000)] # execute the statement 50 times to check execution time

6.64 ms ± 61.7 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [10]:
%timeit -n 50 x_np = np.sin(np.arange(100000))

342 µs ± 8.12 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


* The numpy ndarray is *optimized* for fast mathematical operations on large amounts homogeneous (same-type) data
* Under the hood, efficient  numerical routines are used in numpy (C/FORTRAN compiled code).
* Conversely, the python list support generic python objects. It is more flexible, but far slower.
* Using numpy, we get (almost) the performance of a compiled language, with the flexibility of an interpreted language!

### Array attributes:

The ``ndarray`` object has the following useful attributes:

* ndim, **shape**, size
* **dtype**, itemsize, nbytes

In [11]:
x3 = np.random.randint(10, size=(5, 4, 5))  # Three-dimensional array

In [12]:
# Useful attributes about array dimensions
print(f"x3.ndim:  {x3.ndim}")   # 3: x3 is a 3D array
print(f"x3.shape: {x3.shape}")  # (3, 4, 5)
print(f"x3.size:  {x3.size}")   # 100: x3 contains 5 x 4 x 5 elements

x3.ndim:  3
x3.shape: (5, 4, 5)
x3.size:  100


In [13]:
# Useful attributes about array data type
print(f"x3 dtype: {x3.dtype}")    # x3 is a 64-bit integer
print(f"x3 itemsize (bytes): {x3.itemsize}") # A 64-bit integer occupies 8 bytes
print(f"x3 nbytes: {x3.nbytes}") # 5 x 4 x 5 x 8 = 800 bytes

x3 dtype: int64
x3 itemsize (bytes): 8
x3 nbytes: 800


## 2D array, a.k.a. matrix

It is fairly common to work with 2D arrays. They are equivalent to matrices in linear algebra!

In [14]:
# build a numpy array from a list of lists.
import numpy as np
A = np.array([[1.0, 2.0, 3.0], 
              [6.0, 5.0, 4.0]], dtype=np.float32) 
A

array([[1., 2., 3.],
       [6., 5., 4.]], dtype=float32)

In [15]:
A.ndim

2

In [16]:
A.shape # A has two dimension. The innermost dimension # rows is 2, the outer dimension #n_cols is 3

(2, 3)

In [17]:
A.dtype

dtype('float32')

A really basic operation: add 1 to all the elements of matrix A

In [18]:
A+1

array([[2., 3., 4.],
       [7., 6., 5.]], dtype=float32)

You will learn more about matrix computation in the *Linear Algebra* module. 

Any kind of matrix computation (inverse, matrix multiplication, eigenvalues, eigenvectors, ...) is natively supported in ``numpy``.

# 1D array,  a.k.a. vector 

1D numpy arrays may be seen as vectors, as you probably know from linear algebra

In [19]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In Linear Algebra, there is a distinction between row- and column-vectors.
Is ``x`` a row or a column vector? In fact, this is not even specified!

In [20]:
# A vector (neither row nor column)
x.shape # x has only one dimension. It has length 4.

(4,)

To construct row/column vectors, we use 2D numpy arrays

In [21]:
# A row vector

x_row = np.array([[1, 2, 3, 4]])
x_row.shape

(1, 4)

In [22]:
# A column vector

x_col = np.array([[1], [2], [3], [4]])
x_col.shape

(4, 1)

# Common constructors

How do we define a numpy array?

In [23]:
# From a list of numeric values
np.array([3.14, 6.24, 2.71], dtype=np.float32) # can also specity the data type

array([3.14, 6.24, 2.71], dtype=float32)

In [24]:
# From a list [of list of list...] of numeric values 
np.array([[0, 1], [1, 0]], dtype=np.float32)

array([[0., 1.],
       [1., 0.]], dtype=float32)

In [25]:
np.zeros((4, 3), dtype=np.int64) # all values are 0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
# Special constructors for special matrices
np.ones((3, 4)) # all values are 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
# An Identity Matrix. You will see that that this matrix is useful in Linear Algebra!
np.eye(3) # or np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Common constructors cont'd

Numerical ranges

In [28]:
np.arange(10) # from 0 to 10-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(2, 12) # from 2 to 12-1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(2, 12, 0.5) # start, stop, step

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5])

In [31]:
np.linspace(0, 1, 5) # start, stop, num

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

(Pseudo)-random number generation

In [32]:
np.random.randint(10, size=(2, 2))  # 3x3 matrix with integers from 0 to 9

array([[7, 5],
       [5, 4]])

In [33]:
np.random.randn(2, 3) # 3x3 matrix with values extracted from a standard Gaussian

array([[ 0.58833699, -0.59260019, -1.17318911],
       [ 0.33572749, -0.69054543,  1.70166894]])

In [34]:
np.random.rand(2, 5) # 2x2 matrix with random numbers extracted from the uniform distribution in [0, 1)

array([[0.72080079, 0.00515166, 0.70975674, 0.08717662, 0.29601821],
       [0.21806641, 0.40350752, 0.26276484, 0.83064811, 0.36204292]])

# Arithmetic with numpy


Basic operations ```+ - * /``` are available.

They are applied efficiently in a **vectorized** fashion, with the general objective of avoiding (slow) python ```for``` loops


* Operations between equal-size arrays are applied **element-wise**

In [35]:
res0 = np.ones((3, 3)) + np.eye(3) 
res0

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

* If one operand is scalar, it is repeated to match the dimension of the other operands

In [36]:
1/res0 # It is like: np.ones((3, 3))/res0

array([[0.5, 1. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 1. , 0.5]])

 * More advanced [broadcasting rules](https://numpy.org/devdocs/user/theory.broadcasting.html) define behavior with arrays of different (but compatible) size.  They are out of the scope of this course

In [37]:
#np.random.randn(3, 3, 2) + np.random.randn(3, 2) # this works
#np.random.randn(3, 3, 2) + np.random.randn(3, 3, 1) # this works
#np.random.randn(3, 3, 2) + np.random.randn(3, 3) # this won't work

* Rationale: with a single line of code, instruct the computer to perform several useful operations. Then, the slow nature of Python becomes less critical.

# Universal functions

Perform the same operations on all elements multidimensional arrays. Universal in the sense that they can be applied to 1D, 2D, ... ND arrays.

Many universal functions are *unary* (i.e. they take one operand) and apply element-wise transformations

In [38]:
data = np.random.rand(2, 5)
data

array([[0.96254356, 0.71914295, 0.66173761, 0.4655706 , 0.31170088],
       [0.03310407, 0.8618542 , 0.0390457 , 0.24460359, 0.43501512]])

In [39]:
# Mathematical functions like sin, cos, tan, acos are implemented as unary universal functions
np.sin(data) # np.sin, np.cos, np.tan, np.acos, np.asin, np.exp, np.log, ...

array([[0.8206477 , 0.65874009, 0.61448863, 0.44893275, 0.306678  ],
       [0.03309802, 0.75905101, 0.03903578, 0.24217173, 0.42142411]])

Some universal funtions are *binary* (i.e. they take two operands of equal or compatible size)

In [40]:
x = np.random.randn(5)
y = np.random.randn(5)
print(x)
print(y)

[-1.92321029  0.89922188  1.59307552  0.00970638 -0.43096665]
[ 0.84608626 -1.09544371 -0.9934034   0.15584584 -1.48140164]


In [41]:
# Maximum, minimum, power, ... are binary universal functions
z = np.maximum(x, y) #np.minimum, np.power, np.mod...
z

array([ 0.84608626,  0.89922188,  1.59307552,  0.15584584, -0.43096665])

# Linear Algebra

All sort of linear algebra operations are available. Examples for vectors:

Let us construct the canonical base $\{\overrightarrow {e_1}, \overrightarrow {e_2}, \overrightarrow {e_3}\}$ of $\mathbb{R}^3$

In [42]:
# Canonical base of R^3. Note: e1, e2, e3 are 1D arrays, with 3 elements.
e1 = np.array([1, 0, 0]) 
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

Let us compute the dot product: $ \overrightarrow {e_1} \cdot \overrightarrow {e_2}$

In [43]:
np.dot(e1, e2) # dot product is zero (e1 and e2 are indeed perpendicular)

0

Let us compute the cross product: $ \overrightarrow {e_1} \times \overrightarrow {e_2}$

In [44]:
np.cross(e1, e2) # e1 x e2 = e3, as expected

array([0, 0, 1])

Let us compute $\overrightarrow {e_2} \times (3 \overrightarrow {e_2} + \overrightarrow {e_3} -2\overrightarrow {e_1})$

In [45]:
np.cross(e2, (3*e2 + e3 - 2*e1))

array([1, 0, 2])

No need to study Linear Algebra!

# Linear Algebra

All sort of linear algebra operations are available. Examples for matrices:

In [46]:
I2 = np.eye(2) # 2x2 identity matrix
A = np.random.randn(2, 2)
A

array([[ 0.71134966,  1.45236407],
       [-0.19482015, -0.65100138]])

In [47]:
# This is a matrix multiplication
A @ I2 # or A.dot(I2)

array([[ 0.71134966,  1.45236407],
       [-0.19482015, -0.65100138]])

In [48]:
# Warning: this is an element-wise multiplication!
A * I2

array([[ 0.71134966,  0.        ],
       [-0.        , -0.65100138]])

In [49]:
np.linalg.det(A) # compute determinant of the matrix

-0.18013982564750766

In [50]:
b = np.random.randn(2)
b

array([-0.01757224,  0.43279242])

In [51]:
x = np.linalg.solve(A, b) # solve linear system Ax = b
x

array([ 3.42585326, -1.69003892])

In [52]:
A @ x # indeed, Ax = b!

array([-0.01757224,  0.43279242])

# Aggregations

Operations ''summarizing'' several numerical values to a scalar

In [53]:
A = np.random.randint(0, 4, size=(4, 2))
A

array([[3, 1],
       [2, 0],
       [0, 1],
       [1, 3]])

In [54]:
np.mean(A) # np.sum, np.max, np.min, np.std

1.375

We can optionally provide an ``axis`` parameter. Then, the aggregation is performed over that axis only.

In [55]:
np.mean(A, axis=0) # Aggregate over axis 0 (rows). Then, we are computing the mean of the 2 columns.

array([1.5 , 1.25])

In [56]:
np.mean(A, axis=1) # Aggregate over axis 1 (columns). Then, we are computing the mean of the 4 rows.

array([2. , 1. , 0.5, 2. ])

Note: for multi-dimensional arrays, ``axis`` may be a tuple of all the axes to be aggregated.

# Basic indexing

As lists, numpy ndarrays are indexed by integers starting from 0 and accessed using square brackets notation:

In [57]:
arr1d = np.arange(10) # 0, 1, 2, ..., 9
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr1d[2]

2

For multidimensional arrays, just use multiple indexes separated by commas:

In [59]:
I3 = np.eye(3) # 3x3 identity matrix
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [60]:
I3[1, 1] # elements on the diagonal are 1

1.0

In [61]:
I3[0, 1] # off-diagonal elements are 0

0.0

Numpy arrays are *mutable*:

In [62]:
I3[2, 2] = 2 # arrays are mutable
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 2.]])

# Slicing

Allows extracting a portion of an array. The general syntax is:
```python 
x[start:stop:step]
```

If any of these are unspecified, they default to start=0, stop=size of dimension, step=1. 

Slicing notation for 1D arrays is similar to the one for list:


In [63]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr1d[0:8] # start from 0, step=1, until index < 8. Thus, the last index is 7

array([0, 1, 2, 3, 4, 5, 6, 7])

In [65]:
arr1d[1:9:2] # start from 1, step=2, until index < 8. Thus, the last index is 7

array([1, 3, 5, 7])

In [66]:
arr1d[::-1] # reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Negative indices refer to the end of the array

In [67]:
arr1d[2:-1] # start from index 2 and skip the last 1 element

array([2, 3, 4, 5, 6, 7, 8])

In [68]:
arr1d[1:-2] # start from index 1 and skip the last 2 element

array([1, 2, 3, 4, 5, 6, 7])

# Slicing cont'd

The notation extends naturally to multidimensional arrays

In [69]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
arr2d[1:, 1:]

array([[5, 6],
       [8, 9]])

Slicing can be combined with basic indexing

In [71]:
arr2d[0, :] # first row

array([1, 2, 3])

In [72]:
arr2d[:, 0] # first column

array([1, 4, 7])

# Boolean indexing

Refers to indexing through numpy arrays of booleans. Very useful in practice

In [73]:
data = np.random.randn(3, 4)
data

array([[-1.43282639, -0.14997499,  2.14840982, -0.37472202],
       [-0.61487622,  1.31115675, -0.49263978,  0.89767454],
       [-0.1992075 , -0.44713302, -0.30581415, -0.22482846]])

In [74]:
mask = data < 0 # a numpy array of booleans (boolean mask)
mask

array([[ True,  True, False,  True],
       [ True, False,  True, False],
       [ True,  True,  True,  True]])

In [75]:
arr = data[mask]
arr

array([-1.43282639, -0.14997499, -0.37472202, -0.61487622, -0.49263978,
       -0.1992075 , -0.44713302, -0.30581415, -0.22482846])

Boolean indexing is often used to modify array elements according to a logical condition:

In [76]:
data[data<0] = 0.0 # typical use: change values according to a logical condition
data

array([[0.        , 0.        , 2.14840982, 0.        ],
       [0.        , 1.31115675, 0.        , 0.89767454],
       [0.        , 0.        , 0.        , 0.        ]])

# Boolean indexing cont'd

More complex conditions can  be defined using the operators 

* Logical 'or' ``|``
* Logical 'and' ``&``
* Logical 'not' ``~``
* Equal `==`


In [77]:
data = np.random.randn(3, 4)
data

array([[-0.65212144, -0.89385125, -0.19451964, -1.11151438],
       [ 0.24879799, -1.89833808, -0.92695843, -1.84351881],
       [ 0.53692489,  0.87032674,  1.08541017,  0.12950638]])

In [78]:
mask = (data < -0.6) | (data > 0.6) # a  logical condition using  the 'or' operator |
mask

array([[ True,  True, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True, False]])

In [79]:
mask = (data > 0) & (data < 0.5) # a logical condition using the 'and' operator &
mask

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False, False,  True]])

In [80]:
data[mask] = data[mask] * 10
data[mask]

array([2.4879799 , 1.29506379])

# Fancy indexing

Refers to indexing through an **array** (or a list) of integers 

In [81]:
data = np.random.randn(10, 3)
data

array([[ 0.81149058,  0.4524279 ,  1.07857031],
       [-0.40293114,  0.81993145, -0.86187233],
       [ 0.8847201 ,  0.29423417,  0.47009299],
       [-0.82446259,  0.45326705,  1.39381889],
       [-0.44745771, -0.26330843, -1.27692044],
       [ 1.35764264, -0.59984098,  0.1028096 ],
       [-0.25286258, -0.99690033,  1.69196078],
       [-1.3282131 ,  0.73120965, -0.21225591],
       [ 0.8334875 , -0.07677498,  1.55615623],
       [ 0.6262999 ,  1.52047669,  0.37066378]])

In [82]:
data[[0, 1, 8, 9]] # select the rows 0, 1, 8, 9 of the matrix

array([[ 0.81149058,  0.4524279 ,  1.07857031],
       [-0.40293114,  0.81993145, -0.86187233],
       [ 0.8334875 , -0.07677498,  1.55615623],
       [ 0.6262999 ,  1.52047669,  0.37066378]])

If you provide multiple arrays, the behavior of fancy indexing is different:

In [83]:
data[[0, 1, 9], [1, 2, 0]] # select the elements in position (0,1), (1,2), (9,0)

array([ 0.4524279 , -0.86187233,  0.6262999 ])

# Reshaping

View the data of an array as another array with different dimensions, but same number of elements.

In [84]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [85]:
A = x.reshape(4, 4)#, order="C")
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Note: the matrix A is filled "row by row". This is the default behavior in Python and corresponds to the  *row-major* convention adopted in C language. <br/> 

Other languages like FORTRAN or MATLAB fill matrices by column, according to the *column-major* convention. In numpy, this is forced using the ``order="F"`` option. 

In [86]:
A = x.reshape(4, 4, order="F") # order="C" or "F"
A

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In C, the elements on the same row are close in memory. In FORTRAN, the elements on the same column are close in memory!

# Reshaping cont'd

Let us create another view of our data:

In [87]:
B = x.reshape(2, 8)
B

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

We can now access and also modify the 2D array B

In [88]:
B[1, 7]

15

In [89]:
B[1, 7] = 100
B

array([[  0,   1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13,  14, 100]])

**Warning**: x and B refer to *the same* memory! Thus, also x has been modified. Is this what we wanted?

In [90]:
x # the array x has also been modified!

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14, 100])

To create an *independent* data structure, use ``np.copy``

In [91]:
B_cpy = np.copy(B) # Further changes on B_cpy do not affect x as it refers to a different location in memory